wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705767990.350019
    t:
      1:
      - 5
      - 15
      - 53
      - 55
      2:
      - 5
      - 15
      - 53
      - 55
      3:
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
    viz:
      feature_importances:
        id: wandb/feature_importances/v1
        historyFieldSettings:
          x-axis: _step
          key: feature_importances
      confusion_matrix:
        id: wandb/confusion_matrix/v1
        historyFieldSettings:
          x-axis: _step
          key: confusion_matrix
